# TODO Play with validation
DiscordBotToken: ""
GuildID: ""
# The ID of the channel that the bot will send its welcome message.
PrimaryChannelID: ""
AlertingMethods:
  Twilio:
    AccountSID: ""
    AuthToken: ""
    TwilioPhoneNumber: ""
  Email:
    Auth:
      # Indentity remains empty usually.
      Identity: ""
      # Your email address from your server host provider.
      Username: ""
      # Password to the email account from your server host provider.
      Password: ""
      # URL followed by the port number to your server.
      Host: ""
    # The same email as username listed above.
    From: ""
    # The message that gets sent when a vote is triggered.
    DefaultMessage: ""

Voting:
  RequiredVotes:
    # Number of votes required before an alert is sent or a ban is triggered.
    PanicAlert: 3
    PanicBan: 5
  ContactOnVote:
    # Who will be contacted when a vote is started.
    Discord:
      Users: [""]
      Roles: [""]
    Twilio:
      PhoneNumbers: [""]
    Email:
      Addresses: [""]
  AllowedToVote:
    # Users that will be allowed to start panic votes.
    PanicAlert:
      Users: [""]
      Roles: [""]
    PanicBan:
      Users: [""]
      Roles: [""]
  VoteTimers:
    # Configures how long votes will last.
    PanicAlertVoteTimer: ""
    PanicBanVoteTimer: ""
  Cooldown:
    # Configures how long you must wait between each use of panic commands.
    # Set to -1 for unlimited cooldown.
    PanicAlert: ""
    PanicBan: ""
  RateLimit:
    # Configures how many times the panic commands can be triggered per time period.
    # Set to -1 for unlimited uses.
    PanicAlert:
      Day: 0
      Hour: 0
    PanicBan:
      Day: 0
      Hour: 0
